config/routes.rb
Rails.application.routes.draw do
  root to: "dashboards#show"

  resource :dashboard, only: [:show]

  resources :rambles, only: [:index, :create, :show, :destroy] do
    member do
      post "like" => "ramble_likes#create"
      delete "unlike" => "ramble_likes#destroy"
    end
  end

  resources :users, only: [:show, :index] do
    member do
      post "follow" => "following_relationships#create"
      delete "unfollow" => "following_relationships#destroy"
    end
  end

end

app/models/following_relationship.rb
class FollowingRelationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed_user, class_name: "User"

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :likable, polymorphic: true
end

app/models/ramble.rb
class Ramble < ActiveRecord::Base
  belongs_to :user
  has_many :likes, as: :likable, dependent: :destroy

  def self.paginated(page, per)
    page(page).per(per)
  end

  def self.recent
    order(created_at: :desc)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :rambles

  has_many :followed_user_relationships,
    foreign_key: :follower_id,
    class_name: "FollowingRelationship",
    dependent: :destroy
  has_many :followed_users, through: :followed_user_relationships

  has_many :follower_relationships,
    foreign_key: :followed_user_id,
    class_name: "FollowingRelationship",
    dependent: :destroy

  has_many :followers, through: :follower_relationships

  has_many :likes, dependent: :destroy
  has_many :liked_rambles, through: :likes, source: :likable, source_type: 'Ramble'

  def follow(user)
    follow = followed_user_relationships.create(followed_user: user)
  end

  def following?(user)
    followed_user_ids.include? user.id
  end

  def unfollow(user)
    followed_users.destroy user
  end

  def like(target)
    like = likes.create(likable: target)
  end

  def liked?(target)
    likes.exists?(likable: target)
  end

  def unlike(target)
    likes.find_by(likable: target).destroy
  end

  def self.paginated(page, per)
    page(page).per(per)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @ramble = Ramble.new
    @rambles = Ramble.recent.paginated(params[:page], 3)
  end
end

app/controllers/following_relationships_controller.rb
class FollowingRelationshipsController < ApplicationController
  def create
    followed_user  = User.find(params[:id])
    follow =  current_user.follow followed_user
    redirect_to followed_user
  end

  def destroy
    followed_user  = User.find(params[:id])
    current_user.unfollow followed_user
    redirect_to followed_user
  end
end

app/controllers/ramble_likes_controller.rb
class RambleLikesController < ApplicationController
  def create
    @ramble = Ramble.find(params[:id])
    like = current_user.like @ramble
    redirect_to @ramble
  end

  def destroy
    @ramble = Ramble.find(params[:id])
    current_user.unlike @ramble
    redirect_to @ramble
  end
end

app/controllers/rambles_controller.rb
class RamblesController < ApplicationController
  def index
    @ramble = Ramble.new
    @rambles = Ramble.paginated(params[:page], 5)
  end

  def create
    ramble = current_user.rambles.create(ramble_params)
    redirect_to ramble
  end

  def show
    @ramble = Ramble.find(params[:id])
  end

  def destroy
    ramble = Ramble.find(params[:id])
    ramble.destroy

    redirect_to root_path, notice: "Ramble deleted"
  end

  private

  def ramble_params
    params.require(:ramble).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @rambles = @user.rambles.paginated(params[:page], 3)
  end

  def index
    @users = User.all.paginated(params[:page], 10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<div id=logo>
  <h1><%= link_to 'rambler', root_path %></h1>
</div>

<div id='sign-in-status'>
  <% if signed_in? -%>
    <%= link_to t('layouts.application.sign_out'), sign_out_path, method: :delete %>
    <% else -%>
      <%= link_to t('layouts.application.sign_in'), sign_in_path %>
    <% end -%>
</div>

app/views/dashboards/show.html.erb
<h2>Welcome</h2>

<%= render 'rambles/new', ramble: @ramble %>

<h2 id='rambles-header'>What's up...</h2>

<%= render @rambles %>

<%= paginate @rambles %>

<%= link_to 'view all rambles', rambles_path %>
<br>
<%= link_to 'view all users', users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>rambler</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <div id='outer-wrapper'>
      <%= render "header" %>

      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>">
            <%= value %>
          </div>
        <% end %>
      </div>

      <div id="main-content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/rambles/_new.erb
<div id="new-ramble">
  <% if current_user %>
    <p>I'm thinking...</p>
    <%= form_for(@ramble)  do |f| %>
      <%= f.text_field :body %>
      <%= f.submit "Ramble!" %>
    <% end %>
  <% else %>
    <p><%=link_to "sign in", sign_in_path%> to ramble</p>
  <% end %>
</div>

app/views/rambles/_ramble.erb
<ul>
  <li class="ramble">
    <%= ramble.created_at.strftime("%b %d %Y") %>
  — <%= link_to ramble.user.email, ramble.user %>

    <div class="ramble-text">
      <%= link_to ramble.body, ramble %>
    </div>
  </li>
<ul>

app/views/rambles/index.html.erb
<h1>What's up...</h1>
<%=link_to 'back to dashboard', dashboard_path %>

<div id="all-rambles">
  <%= render @rambles %>
  <%= paginate @rambles %>
</div>

app/views/rambles/show.html.erb
<h2>Just sayin...</h2>

<div id="show-ramble">
  <p><%= @ramble.body %></p>
  <%= pluralize(@ramble.likes.count, "likes") %>
</div>

<% if current_user && current_user == @ramble.user %>
  <%= button_to "Delete", @ramble, method: :delete %>
<% else %>
  <% if current_user.liked? @ramble%>
    <%= button_to "Unlike", unlike_ramble_path(@ramble), method: :delete %>
  <%else%>
    <%= button_to "Like", like_ramble_path(@ramble) %>
  <%end%>
<% end %>

<%= link_to 'home', root_path %>

app/views/users/_form.html.erb
<div class='text-field'>
  <%= form.label :email %>
  <%= form.text_field :email, :type => 'email' %>
</div>

<div class='password-field'>
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/_user.erb
<ul>
  <li class="user">
    <%= link_to user.email, user_path(user.id) %>
    <p>rambler since: <%= user.created_at.strftime("%b %d %Y") %>
  </li>
<ul>

app/views/users/index.html.erb
<h2>Check em out</h2>
<%= render @users %>

app/views/users/new.html.erb
<div id='clearance' class='sign-up'>
  <h2><%= t('.title') %></h2>

  <%= form_for @user do |form| %>
    <%= render :partial => '/users/form', :object => form %>

    <div class='submit-field'>
      <%= form.submit %>
    </div>

    <div class='other-links'>
      <%= link_to t('.sign_in'), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>
<div id ="followers">
  <%= pluralize(@user.followers.count, "follower") %></p>
</div>

<%if signed_in?%>
  <%if current_user != @user %>
    <%if current_user.following? @user %>
      <%= button_to "Unfollow", unfollow_user_path(@user), method: :delete %>
    <%else%>
      <%= button_to "Follow", follow_user_path(@user) %>
    <%end%>
  <%end%>
<% end %>

<%= render @rambles %>
<%= paginate @rambles %>